if (COMP_NAME STREQUAL gptl)
  string(APPEND CFLAGS " -DHAVE_SLASHPROC")
endif()
string(APPEND CPPDEFS " -DLINUX")
if (DEBUG)
  string(APPEND FFLAGS " -check all -ftrapuv -init=snan")
endif()
set(NETCDF_PATH "$ENV{NETCDF_ROOT}")
set(PNETCDF_PATH "$ENV{PNETCDF_HOME}")
set(PIO_FILESYSTEM_HINTS "lustre")
string(APPEND SLIBS " -lpmi -L${NETCDF_C_HOME}/lib -lnetcdf -L${NETCDF_FORTRAN_HOME}/lib -lnetcdff -L$ENV{MKLROOT}/lib/intel64/ -lmkl_rt $ENV{PARALLEL_NETCDF_HOME}/lib")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
